#!/usr/bin/env bash
# Generate the six Stage-A jobman configs from stage_a_cells.sh (the single
# source of truth for the factorial). Re-run after editing cells or hooks:
#   bash tpu/jobman/gen_configs.sh
# Then: ~/.venvs/jobman/bin/jobman create tpu/jobman/configs/stagea_<cell>.yaml
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
source "$HERE/../stage_a_cells.sh"
OUT="$HERE/configs"; mkdir -p "$OUT"
BUNDLE_URL=gs://sk7524-tinker-tpu-us-east5/code-bundles/stagea-league.tar.gz

# Problem dimension. Same regularizer factorial on each problem:
#   erdos: reference numeric-construction problem (dense signal, record baselines)
#   jssp:  frontier_algo problem 46 -- C++ code discovery; knobs fc46-proven
#          (TTD_PROBLEM_TYPE=46, TTD_FCALGO_MAX_CASES=0, EVAL_TIMEOUT=180)
#   ac1:   ac_inequalities (Stage B) -- N arms only: Stage A settled that plain
#          no-regularizer is the reference config for the objective comparison.
#          Measure-only KL pass explicitly OFF (18k seqs; Erdos lesson).
PROBLEMS=("erdos" "jssp" "ac1")

# Model dimension (Phase 2 slice of the plan): qwen = full Stage-A factorial;
# gemma = N arms only (Stage A settled the regularizer question), cell prefix
# g-, engine/client knobs resolved by the g-* cases in cell_worker/launch_cell.
MODELS=("qwen" "gemma")

# Generation-2 cells: contaminated by the frozen-weights era (Erdos trains
# silently OOMed; grpo-k-j hit the same wall via penalty-pass + fat tiles).
# A gen-2 name gives them a FRESH run dir, GCS path, wandb run and tree, while
# the gen-1 dirs remain in place as the archive of the contaminated runs.
RERUN2="grpo-n grpo-k grpo-r ttd-n ttd-k ttd-r grpo-n-j grpo-k-j grpo-r-j ttd-n-j ttd-k-j ttd-r-j"

for model in "${MODELS[@]}"; do
for prob in "${PROBLEMS[@]}"; do
for row in "${STAGE_A_CELLS[@]}"; do
  IFS='|' read -r cell adv elite gpb gsz kl rr <<<"$row"
  # gemma runs the objective comparison only: N arms, all three problems.
  if [ "$model" = "gemma" ]; then
    { [ "$kl" != "0" ] || [ "$rr" != "0" ]; } && continue
    cell="g-${cell}"
  fi
  if [ "$prob" = "jssp" ]; then
    cell="${cell}-j"
    prob_env_block="    TTD_ENV: frontier_algo
    TTD_PROBLEM_TYPE: \"46\"
    TTD_FCALGO_MAX_CASES: \"0\"
    EVAL_TIMEOUT: \"180\"
    TTD_KL_MEASURE_EVERY: \"0\""
  elif [ "$prob" = "ac1" ]; then
    # Stage B: objective comparison only -- skip K and R rows.
    { [ "$kl" != "0" ] || [ "$rr" != "0" ]; } && continue
    cell="${cell}-a"
    prob_env_block="    TTD_ENV: ac_inequalities
    TTD_KL_MEASURE_EVERY: \"0\""
  else
    prob_env_block="    TTD_ENV: erdos_min_overlap"
  fi
  # Keep the 12 original qwen erdos/jssp YAMLs byte-identical: their jssp
  # block historically had no KLMEAS line and launch_cell defaults it to 1.
  if [ "$model" = "qwen" ] && [ "$prob" = "jssp" ]; then
    prob_env_block="    TTD_ENV: frontier_algo
    TTD_PROBLEM_TYPE: \"46\"
    TTD_FCALGO_MAX_CASES: \"0\"
    EVAL_TIMEOUT: \"180\""
  fi
  gen_env_block=""
  if [ "$model" = "gemma" ]; then
    gen_env_block="    RUN_DIR_NAME: stageB-${cell}
    EXPERIMENT_NAME: stageB-${cell}"
  elif [ "$prob" = "ac1" ]; then
    gen_env_block="    RUN_DIR_NAME: stageB-${cell}
    EXPERIMENT_NAME: stageB-${cell}"
  else
    for _rc in $RERUN2; do
      [ "$_rc" = "$cell" ] && gen_env_block="    RUN_DIR_NAME: stageA2-${cell}
    EXPERIMENT_NAME: stageA2-${cell}"
    done
  fi
  cat > "$OUT/stagea_${cell}.yaml" <<YAML
# GENERATED by tpu/jobman/gen_configs.sh -- edit stage_a_cells.sh, not this file.
# Stage-A cell ${cell} (${prob}): adv=${adv} elite=${elite} batch=${gpb}x${gsz} kl=${kl} restart_ratio=${rr}
job:
  name: sk7524-stagea-${cell}
  env_type: null
  loop: true
  remote_user: sk7524_princeton_edu
  worker_num: auto

tpu:
  allocation_mode: "queued-resources"
  accelerator: v5p-32
  name: sk7524-stagea-${cell}
  zone: us-east5-a
  version: v2-alpha-tpuv5
  pricing: spot
  flags:
    - "--project=vision-mix"

gcsfuse:
  bucket_name: sk7524-tinker-tpu-us-east5
  mount_path: /home/sk7524_princeton_edu/gcs

ssh:
  private_key: ~/.ssh/jobman_tpu_ed25519
  identities:
    - private_key: ~/.ssh/jobman_tpu_ed25519
      public_key: ~/.ssh/jobman_tpu_ed25519.pub
      config_entry: |
        Host 10.* 34.* 35.* 8.* 104.* 136.*
          IdentityFile ~/.ssh/jobman_tpu_ed25519
          IdentitiesOnly yes
          StrictHostKeyChecking no
          UserKnownHostsFile /dev/null

resumable:
  enabled: true
  run_id: auto
  run_id_prefix: stagea-${cell}
  local_cache_root: /n/fs/vision-mix/sk7524/jobman-runs
  remote_gcs_cache_root: /home/sk7524_princeton_edu/gcs/jobman-runs
  remote_local_cache_root: /tmp/jobman-runs
  retry_sleep_seconds: 60
  lease:
    type: local
    poll_seconds: 30
  run_spec:
    experiment: stage-a-regularization
    cell: ${cell}
    objective: ${adv}
    elite_slots: ${elite}
    batch_shape: ${gpb}x${gsz}
    kl_penalty_coef: ${kl}
    restart_ratio: ${rr}
    steps: 15
    problem: ${prob}
  env:
    CELL: ${cell}
    TTD_ADV_ESTIMATOR: ${adv}
    TTD_ELITE_SLOTS: "${elite}"
    GROUPS_PER_BATCH: "${gpb}"
    GROUP_SIZE: "${gsz}"
    KL_PENALTY_COEF: "${kl}"
    TTD_RESTART_RATIO: "${rr}"
    NUM_EPOCHS: "15"
${gen_env_block}
${prob_env_block}
    SKYRLTPU_BUNDLE_URL: ${BUNDLE_URL}
  prepare:
    workers: all
    timeout: 0
    command: |
      set -euxo pipefail
      wait_for_apt() {
        local waited=0
        while sudo fuser /var/lib/dpkg/lock-frontend /var/lib/dpkg/lock /var/cache/apt/archives/lock >/dev/null 2>&1; do
          (( waited >= 600 )) && return 1
          sleep 5; waited=\$((waited + 5))
        done
      }
      # Skip apt entirely once everything is present: prepare re-runs on EVERY
      # loop iteration, and unattended-upgrades holding the dpkg lock 10+ min
      # (seen live on grpo-k w2) must not fail an otherwise-healthy retry.
      if ! { command -v git && command -v tmux && command -v g++; } >/dev/null 2>&1; then
        wait_for_apt; sudo apt-get update -y
        wait_for_apt; sudo DEBIAN_FRONTEND=noninteractive apt-get install -y git curl tmux python3 python3-venv python3-pip build-essential
      fi
      command -v uv >/dev/null 2>&1 || curl -LsSf https://astral.sh/uv/install.sh | sh
      export PATH="\$HOME/.local/bin:\$PATH"
      mkdir -p "\$HOME/gcs/skyrl-checkpoints" "\$HOME/skyrl-runs" "\$HOME/skyrl-logs"
      # Unpack the league code bundle when absent or stale. Staleness and the
      # copy go through gsutil, NOT the gcsfuse mount: fuse attribute caching
      # served a same-path re-upload's OLD size for its TTL, so prepare saw
      # "unchanged", skipped the unpack, and hosts rebuilt engines from stale
      # code (bit the tile-fix rollout live).
      BUNDLE_URL="${BUNDLE_URL}"
      DEST="\$HOME/SkyRLTpu-league"
      want=\$(gsutil stat "\$BUNDLE_URL" | awk '/Content-Length/ {print \$2}')
      test -n "\$want"
      have=\$(cat "\$DEST/.bundle-size" 2>/dev/null || echo none)
      if [ "\$want" != "\$have" ]; then
        gsutil -q cp "\$BUNDLE_URL" /tmp/stagea-bundle.tar.gz
        rm -rf "\$DEST.new"; mkdir -p "\$DEST.new"
        tar -xzf /tmp/stagea-bundle.tar.gz -C "\$DEST.new"
        test -x "\$DEST.new/tpu/jobman/cell_worker.sh"
        test -f "\$DEST.new/third_party/discover/.env"
        echo "\$want" > "\$DEST.new/.bundle-size"
        rm -rf "\$DEST.old"; [ -d "\$DEST" ] && mv "\$DEST" "\$DEST.old" || true
        mv "\$DEST.new" "\$DEST"
      fi
  monitor:
    workers: 0
    timeout: 0
    command: |
      export PATH="\$HOME/.local/bin:\$PATH"
      bash "\$HOME/SkyRLTpu-league/tpu/jobman/cell_monitor.sh"
  sync:
    workers: 0
    timeout: 600
    command: |
      bash "\$HOME/SkyRLTpu-league/tpu/jobman/cell_sync.sh"
  completion_probe:
    workers: 0
    timeout: 120
    command: |
      bash "\$HOME/SkyRLTpu-league/tpu/jobman/cell_probe.sh"

command:
  cmd: |
    set -euo pipefail
    export PATH="\$HOME/.local/bin:\$PATH"
    bash "\$HOME/SkyRLTpu-league/tpu/jobman/cell_worker.sh"
  workers: "all"
YAML
  echo "wrote $OUT/stagea_${cell}.yaml"
done
done
done
