#!/usr/bin/env bash
# Generate the six Stage-A jobman configs from stage_a_cells.sh (the single
# source of truth for the factorial). Re-run after editing cells or hooks:
#   bash tpu/jobman/gen_configs.sh
# Then: ~/.venvs/jobman/bin/jobman create tpu/jobman/configs/stagea_<cell>.yaml
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
source "$HERE/../stage_a_cells.sh"
OUT="$HERE/configs"; mkdir -p "$OUT"
BUNDLE_REMOTE=/home/sk7524_princeton_edu/gcs/code-bundles/stagea-league.tar.gz

# Problem dimension. Same regularizer factorial on each problem:
#   erdos: reference numeric-construction problem (dense signal, record baselines)
#   jssp:  frontier_algo problem 46 -- C++ code discovery; knobs fc46-proven
#          (TTD_PROBLEM_TYPE=46, TTD_FCALGO_MAX_CASES=0, EVAL_TIMEOUT=180)
PROBLEMS=("erdos" "jssp")

for prob in "${PROBLEMS[@]}"; do
for row in "${STAGE_A_CELLS[@]}"; do
  IFS='|' read -r cell adv elite gpb gsz kl rr <<<"$row"
  if [ "$prob" = "jssp" ]; then
    cell="${cell}-j"
    prob_env_block="    TTD_ENV: frontier_algo
    TTD_PROBLEM_TYPE: \"46\"
    TTD_FCALGO_MAX_CASES: \"0\"
    EVAL_TIMEOUT: \"180\""
  else
    prob_env_block="    TTD_ENV: erdos_min_overlap"
  fi
  cat > "$OUT/stagea_${cell}.yaml" <<YAML
# GENERATED by tpu/jobman/gen_configs.sh -- edit stage_a_cells.sh, not this file.
# Stage-A cell ${cell} (${prob}): adv=${adv} elite=${elite} batch=${gpb}x${gsz} kl=${kl} restart_ratio=${rr}
job:
  name: sk7524-stagea-${cell}
  env_type: null
  loop: true
  remote_user: sk7524_princeton_edu
  worker_num: auto

tpu:
  allocation_mode: "queued-resources"
  accelerator: v5p-32
  name: sk7524-stagea-${cell}
  zone: us-east5-a
  version: v2-alpha-tpuv5
  pricing: spot
  flags:
    - "--project=vision-mix"

gcsfuse:
  bucket_name: sk7524-tinker-tpu-us-east5
  mount_path: /home/sk7524_princeton_edu/gcs

ssh:
  private_key: ~/.ssh/jobman_tpu_ed25519
  identities:
    - private_key: ~/.ssh/jobman_tpu_ed25519
      public_key: ~/.ssh/jobman_tpu_ed25519.pub
      config_entry: |
        Host 10.* 34.* 35.* 8.* 104.* 136.*
          IdentityFile ~/.ssh/jobman_tpu_ed25519
          IdentitiesOnly yes
          StrictHostKeyChecking no
          UserKnownHostsFile /dev/null

resumable:
  enabled: true
  run_id: auto
  run_id_prefix: stagea-${cell}
  local_cache_root: /n/fs/vision-mix/sk7524/jobman-runs
  remote_gcs_cache_root: /home/sk7524_princeton_edu/gcs/jobman-runs
  remote_local_cache_root: /tmp/jobman-runs
  retry_sleep_seconds: 60
  lease:
    type: local
    poll_seconds: 30
  run_spec:
    experiment: stage-a-regularization
    cell: ${cell}
    objective: ${adv}
    elite_slots: ${elite}
    batch_shape: ${gpb}x${gsz}
    kl_penalty_coef: ${kl}
    restart_ratio: ${rr}
    steps: 15
    problem: ${prob}
  env:
    CELL: ${cell}
    TTD_ADV_ESTIMATOR: ${adv}
    TTD_ELITE_SLOTS: "${elite}"
    GROUPS_PER_BATCH: "${gpb}"
    GROUP_SIZE: "${gsz}"
    KL_PENALTY_COEF: "${kl}"
    TTD_RESTART_RATIO: "${rr}"
    NUM_EPOCHS: "15"
${prob_env_block}
    SKYRLTPU_BUNDLE_PATH: ${BUNDLE_REMOTE}
  prepare:
    workers: all
    timeout: 0
    command: |
      set -euxo pipefail
      wait_for_apt() {
        local waited=0
        while sudo fuser /var/lib/dpkg/lock-frontend /var/lib/dpkg/lock /var/cache/apt/archives/lock >/dev/null 2>&1; do
          (( waited >= 600 )) && return 1
          sleep 5; waited=\$((waited + 5))
        done
      }
      wait_for_apt; sudo apt-get update -y
      wait_for_apt; sudo DEBIAN_FRONTEND=noninteractive apt-get install -y git curl tmux python3 python3-venv python3-pip build-essential
      command -v uv >/dev/null 2>&1 || curl -LsSf https://astral.sh/uv/install.sh | sh
      export PATH="\$HOME/.local/bin:\$PATH"
      mkdir -p "\$HOME/gcs/skyrl-checkpoints" "\$HOME/skyrl-runs" "\$HOME/skyrl-logs"
      # Unpack the league code bundle (visible through the gcsfuse mount) when
      # absent or stale. Stale-detection via the bundle's byte size marker.
      BUNDLE="${BUNDLE_REMOTE}"
      DEST="\$HOME/SkyRLTpu-league"
      test -f "\$BUNDLE"
      want=\$(stat -c%s "\$BUNDLE")
      have=\$(cat "\$DEST/.bundle-size" 2>/dev/null || echo none)
      if [ "\$want" != "\$have" ]; then
        rm -rf "\$DEST.new"; mkdir -p "\$DEST.new"
        tar -xzf "\$BUNDLE" -C "\$DEST.new"
        test -x "\$DEST.new/tpu/jobman/cell_worker.sh"
        test -f "\$DEST.new/third_party/discover/.env"
        echo "\$want" > "\$DEST.new/.bundle-size"
        rm -rf "\$DEST.old"; [ -d "\$DEST" ] && mv "\$DEST" "\$DEST.old" || true
        mv "\$DEST.new" "\$DEST"
      fi
  monitor:
    workers: 0
    timeout: 0
    command: |
      export PATH="\$HOME/.local/bin:\$PATH"
      bash "\$HOME/SkyRLTpu-league/tpu/jobman/cell_monitor.sh"
  sync:
    workers: 0
    timeout: 600
    command: |
      bash "\$HOME/SkyRLTpu-league/tpu/jobman/cell_sync.sh"
  completion_probe:
    workers: 0
    timeout: 120
    command: |
      bash "\$HOME/SkyRLTpu-league/tpu/jobman/cell_probe.sh"

command:
  cmd: |
    set -euo pipefail
    export PATH="\$HOME/.local/bin:\$PATH"
    bash "\$HOME/SkyRLTpu-league/tpu/jobman/cell_worker.sh"
  workers: "all"
YAML
  echo "wrote $OUT/stagea_${cell}.yaml"
done
done
