#!/usr/bin/env bash
# Generate the ctrl-rerun league jobman configs (one v5p-64 per arm).
#   bash tpu/jobman/league_gen_configs.sh
# Arms answer "why did league-ctrl do so well?" under the fixed harness:
#   L-ctrl-n : ctrl config (lambda=0), zero restarts       -- capability alone?
#   L-ctrl-r : ctrl + decay restart (<1% of life peak, 3 consecutive steps)
#   L-ctrl-x : ctrl + SCRIPTED restart after step 8 (the historical schedule:
#              life 0 ran 9 steps, then the accidental reset that paid 91x)
#   L-ours-n : ours config (lambda=0.1 cross-CE), zero restarts
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$HERE/configs"; mkdir -p "$OUT"
BUNDLE_URL=gs://sk7524-tinker-tpu-us-east5/code-bundles/stagea-league.tar.gz

# cell|cross|restart_ratio|restart_consec|restart_at
ARMS=(
  "L-ctrl-n|0|0|3|-1"
  "L-ctrl-r|0|100|3|-1"
  "L-ctrl-x|0|0|3|8"
  "L-ours-n|0.1|0|3|-1"
)

for row in "${ARMS[@]}"; do
  IFS='|' read -r cell cross rr consec at <<<"$row"
  cat > "$OUT/ctrlrerun_${cell}.yaml" <<YAML
# GENERATED by tpu/jobman/league_gen_configs.sh -- edit that script, not this.
# ctrl-rerun arm ${cell}: cross=${cross} restart_ratio=${rr} consec=${consec} at_step=${at}
job:
  name: sk7524-ctrlrerun-${cell}
  env_type: null
  loop: true
  remote_user: sk7524_princeton_edu
  worker_num: auto

tpu:
  allocation_mode: "queued-resources"
  accelerator: v5p-64
  name: sk7524-ctrlrerun-${cell}
  zone: us-east5-a
  version: v2-alpha-tpuv5
  pricing: spot
  flags:
    - "--project=vision-mix"

gcsfuse:
  bucket_name: sk7524-tinker-tpu-us-east5
  mount_path: /home/sk7524_princeton_edu/gcs

ssh:
  private_key: ~/.ssh/jobman_tpu_ed25519
  identities:
    - private_key: ~/.ssh/jobman_tpu_ed25519
      public_key: ~/.ssh/jobman_tpu_ed25519.pub
      config_entry: |
        Host 10.* 34.* 35.* 8.* 104.* 136.*
          IdentityFile ~/.ssh/jobman_tpu_ed25519
          IdentitiesOnly yes
          StrictHostKeyChecking no
          UserKnownHostsFile /dev/null

resumable:
  enabled: true
  run_id: auto
  run_id_prefix: ctrlrerun-${cell}
  local_cache_root: /n/fs/vision-mix/sk7524/jobman-runs
  remote_gcs_cache_root: /home/sk7524_princeton_edu/gcs/jobman-runs
  remote_local_cache_root: /tmp/jobman-runs
  retry_sleep_seconds: 60
  lease:
    type: local
    poll_seconds: 30
  run_spec:
    experiment: ctrl-rerun
    cell: ${cell}
    cross_weight: ${cross}
    restart_ratio: ${rr}
    restart_consec: ${consec}
    restart_at_step: ${at}
    steps: 20
  env:
    CELL: ${cell}
    RUN_DIR_NAME: ctrlrerun-${cell}
    EXPERIMENT_NAME: ctrlrerun-${cell}
    TTD_CROSS_WEIGHT: "${cross}"
    TTD_RESTART_RATIO: "${rr}"
    TTD_RESTART_CONSEC: "${consec}"
    TTD_RESTART_AT_STEP: "${at}"
    NUM_EPOCHS: "20"
    SKYRLTPU_BUNDLE_URL: ${BUNDLE_URL}
  prepare:
    workers: all
    timeout: 0
    command: |
      set -euxo pipefail
      wait_for_apt() {
        local waited=0
        while sudo fuser /var/lib/dpkg/lock-frontend /var/lib/dpkg/lock /var/cache/apt/archives/lock >/dev/null 2>&1; do
          (( waited >= 600 )) && return 1
          sleep 5; waited=\$((waited + 5))
        done
      }
      if ! { command -v git && command -v tmux && command -v g++; } >/dev/null 2>&1; then
        wait_for_apt; sudo apt-get update -y
        wait_for_apt; sudo DEBIAN_FRONTEND=noninteractive apt-get install -y git curl tmux python3 python3-venv python3-pip build-essential
      fi
      command -v uv >/dev/null 2>&1 || curl -LsSf https://astral.sh/uv/install.sh | sh
      export PATH="\$HOME/.local/bin:\$PATH"
      mkdir -p "\$HOME/gcs/skyrl-checkpoints" "\$HOME/skyrl-runs" "\$HOME/skyrl-logs"
      BUNDLE_URL="${BUNDLE_URL}"
      DEST="\$HOME/SkyRLTpu-league"
      want=\$(gsutil stat "\$BUNDLE_URL" | awk '/Content-Length/ {print \$2}')
      test -n "\$want"
      have=\$(cat "\$DEST/.bundle-size" 2>/dev/null || echo none)
      if [ "\$want" != "\$have" ]; then
        gsutil -q cp "\$BUNDLE_URL" /tmp/stagea-bundle.tar.gz
        rm -rf "\$DEST.new"; mkdir -p "\$DEST.new"
        tar -xzf /tmp/stagea-bundle.tar.gz -C "\$DEST.new"
        test -x "\$DEST.new/tpu/jobman/league_worker.sh"
        test -f "\$DEST.new/third_party/discover/.env"
        echo "\$want" > "\$DEST.new/.bundle-size"
        rm -rf "\$DEST.old"; [ -d "\$DEST" ] && mv "\$DEST" "\$DEST.old" || true
        mv "\$DEST.new" "\$DEST"
      fi
  monitor:
    workers: 0
    timeout: 0
    command: |
      export PATH="\$HOME/.local/bin:\$PATH"
      bash "\$HOME/SkyRLTpu-league/tpu/jobman/league_monitor.sh"
  sync:
    workers: 0
    timeout: 600
    command: |
      bash "\$HOME/SkyRLTpu-league/tpu/jobman/cell_sync.sh"
  completion_probe:
    workers: 0
    timeout: 120
    command: |
      bash "\$HOME/SkyRLTpu-league/tpu/jobman/cell_probe.sh"

command:
  cmd: |
    set -euo pipefail
    export PATH="\$HOME/.local/bin:\$PATH"
    bash "\$HOME/SkyRLTpu-league/tpu/jobman/league_worker.sh"
  workers: "all"
YAML
  echo "wrote $OUT/ctrlrerun_${cell}.yaml"
done
