"""Generate the Stage J "continuation" yamls: resume a finished gen-0 cell IN PLACE on a
tpu-v6e-32 pool worker and run it to 45 total optimizer steps (NUM_EPOCHS 15 -> 45).

Why: the Mixture-of-Models gen-1 children (muse/gemma on a qwen seed-i tree, 15 steps) spend
15 qwen + 15 own-model gen-0 + 15 gen-1 = 45 steps of compute. The compute-matched control is
the parent continuing ALONE on its own tree, own weights and own optimizer to 45 steps. Reusing
GCS_RUN makes the cell RESUME from the last durable snapshot (weights, tree, metrics), so the
control is literally the same run carrying on, just on v6e instead of v5p.

Template: v6e32-cell-template.yaml = the gemma cell another session already resumed on v6e
(stageB2-g-v32-ttd-n-v6e): 2+6 layout (VMs 0-1 trainer TP8/FSDP1, VMs 2-7 TP4 engines) with the
physical-topology partner selection in its embedded wrapper. Only the run-identifying envs are
swapped here; the wrapper and resources are untouched.

    python gen_cont45_v6e.py            # writes cont45-*-v6e.yaml next to this file
"""
from __future__ import annotations

import pathlib

import yaml

HERE = pathlib.Path(__file__).resolve().parent
TEMPLATE = HERE / "v6e32-cell-template.yaml"
BUCKET = "gs://sk7524-tinker-tpu-us-east5"
BUNDLE = {21: f"{BUCKET}/code-bundles/tpuswarm-skyrl-v5p32-cells-v21.tar.gz",
          23: f"{BUCKET}/code-bundles/tpuswarm-skyrl-v5p32-cells-v23.tar.gz"}
EXTRA_TTD_ENV = "TINKER_API_KEY=tml-local-skyrl-no-auth TTD_ADV_PIECEWISE_ALPHA=1.0"
TOTAL_STEPS = 45

# tag -> (gen-0 run to continue, CELL, bundle the run was produced with, LR, model)
RUNS = {
    "q-orig": ("stageC-pwc-n", "pwc-n", 21, "1.5e-4", "qwen"),
    "q-rep1": ("stageG-q-rep1", "pwc-n", 23, "1.5e-4", "qwen"),
    "q-rep2": ("stageG-q-rep2", "pwc-n", 23, "1.5e-4", "qwen"),
    "g-orig": ("stageB2-g-pwc-n", "g-pwc-n", 21, "4e-5", "gemma"),
    "g-rep1": ("stageG-g-rep1", "g-pwc-n", 23, "4e-5", "gemma"),
    "g-rep2": ("stageG-g-rep2", "g-pwc-n", 23, "4e-5", "gemma"),
}

# Model-specific v6e trainer/engine caches and the per-call token budget.
# gemma: exactly what the template ran with (one 10240-token row per fb call).
# qwen: cell_worker defaults are MAXTGT 22528 / BUDGET 73728 (v5p packed ~3 rows); on 8 v6e
# chips (32 GB each) at TP8/FSDP1 we take ONE max-length row per call, the same rule the
# gemma port used. Fresh cache prefixes: first compile is slow, later placements reuse them.
MODEL_ENV = {
    "gemma": {
        "TUNIX_TRAIN_TOKEN_BUDGET": "10240",
        "TUNIX_JAX_CACHE_GCS": f"{BUCKET}/jax-compile-cache-v6e-gemma4-tp8-fsdp1-r32-s10240-b10240-cells-v1",
        "VLLM_XLA_CACHE_GCS": f"{BUCKET}/vllm-xla-cache-v6e-gemma4-31b-tp4-16k-v1",
    },
    "qwen": {
        "HF_CACHE_GCS": f"{BUCKET}/hf-cache-qwen35-v1",
        "TUNIX_TRAIN_TOKEN_BUDGET": "22528",
        "TUNIX_JAX_CACHE_GCS": f"{BUCKET}/jax-compile-cache-v6e-qwen35-tp8-fsdp1-r32-s22528-b22528-cells-v1",
        "VLLM_XLA_CACHE_GCS": f"{BUCKET}/vllm-xla-cache-v6e-qwen35-tp4-22k-v1",
    },
}


def build(tag: str) -> pathlib.Path:
    run, cell, bundle_v, lr, model = RUNS[tag]
    doc = yaml.safe_load(TEMPLATE.read_text())
    name = f"cont45-{tag}-v6e"
    doc["name"] = name
    env = doc["envs"]
    env["TPUSWARM_SKYRL_BUNDLE_URL"] = BUNDLE[bundle_v]
    env["TPUSWARM_BUNDLE_ID"] = f"v5p32-cells-v{bundle_v}-{name}"
    env["CELL"] = cell
    env["RUN_DIR_NAME"] = run
    env["EXPERIMENT_NAME"] = run
    env["GCS_RUN"] = f"{BUCKET}/skyrl-runs/{run}"
    env["TTD_ADV_ESTIMATOR"] = "piecewise_valid_entropic_centered"
    env["EXTRA_TTD_ENV"] = EXTRA_TTD_ENV
    env["LEARNING_RATE"] = lr
    env["NUM_EPOCHS"] = str(TOTAL_STEPS)
    for k in ("HF_CACHE_GCS", "TUNIX_TRAIN_TOKEN_BUDGET", "TUNIX_JAX_CACHE_GCS", "VLLM_XLA_CACHE_GCS"):
        env.pop(k, None)
    env.update(MODEL_ENV[model])
    # every value in envs must be a string for SkyPilot
    doc["envs"] = {k: (str(v) if not isinstance(v, str) else v) for k, v in env.items()}

    header = (
        f"# Stage J continuation control: {run} resumed IN PLACE on tpu-v6e-32 and run to\n"
        f"# {TOTAL_STEPS} total steps ({model}, {cell}, centered piecewise, LR {lr}, bundle v{bundle_v} = the\n"
        f"# bundle that produced its checkpoints). Same GCS_RUN => resume of weights + tree + metrics;\n"
        f"# nothing is re-seeded. Compute-matched control for the gen-1 children (15+15+15 = 45).\n"
        f"# Generated by gen_cont45_v6e.py from v6e32-cell-template.yaml (2+6 v6e layout).\n"
    )
    out = HERE / f"{name}.yaml"
    out.write_text(header + yaml.safe_dump(doc, sort_keys=False, width=100000))
    return out


if __name__ == "__main__":
    for t in RUNS:
        p = build(t)
        print(p.name)
